# -*- coding: utf-8 -*-
"""Actividad_9_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Jss1Fg3F5xPpAlwuGXJf5F04ZnrLtSo
"""

historial5 = (8520, 9510, 7530, 3570, 1590)

#Opción 1 monto maximo
def gasto_max_toto(tupla):
    max = 0
    for monto in tupla:
        if monto > max: max = monto
    return f'El valor máximo de atención gastada en Toto es de {max}'

#Opción 2 monto maximo
def max_toto(tupla):
    return max(tupla)

gasto_max_toto(historial5)
max_toto(historial5)